language: node_js
node_js:
  - "12"
services:
  - docker

script:
  - echi "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t einyao/use-dockerfile:1.0.0
  - docker push einyao/use-dockerfile:1.0.0
